# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^\.git/.*$
    -   id: end-of-file-fixer
        exclude: ^\.git/.*$
    -   id: check-yaml
        args:
        - --allow-multiple-documents
        exclude: >
            (?x)^(
                tests/.*|
                data_dir/scylla\.yaml|
                sdcm/k8s_configs/minio/templates/.*|
                sdcm/k8s_configs/provisioner/templates/.*
            )$
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-aws-credentials
    -   id: detect-private-key
        exclude: ^data_dir/ssl_conf/.*$

-   repo: local
    hooks:
    -   id: autopep8
        name: autopep8
        entry: autopep8 -i -j 2 --max-line-length=120 --ignore=E226,E24,W50,W690,E402
        language: system
        types: [python]

    -   id: pylint
        name: pylint
        entry: pylint -j 2 -d consider-using-f-string
        language: system
        exclude: ^docker/alternator-dns/.*$
        types: [python]

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v5.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        language_version: 16.15.1
