# manual on creating loader AMI's: see docs/new_loader_ami.md
# AMIs from branch-perf-v8 with non-shardware driver
use_prepared_loaders: true
ami_id_loader: 'scylla-qa-loader-ami-v9'
ami_loader_user: 'centos'
